"""Multi-agent research system — multiple tools, multiple @dura agents.

This example shows a fixed pipeline: research → analyze → write.
Each step is a @dura agent with its own tools and Temporal event history.

For an example where the LLM decides which agents to call dynamically,
see stochastic_agents.py.
"""

import asyncio

from langchain_anthropic import ChatAnthropic
from langchain_core.messages import HumanMessage, SystemMessage, ToolMessage
from langchain_core.tools import tool

from duralang import dura

# ── Tools ────────────────────────────────────────────────────────────────────


@tool
def web_search(query: str) -> str:
    """Search the web for current information."""
    return (
        f"Search results for '{query}':\n"
        f"1. Recent advances in {query} show significant progress...\n"
        f"2. Experts predict major breakthroughs in {query} by 2027...\n"
        f"3. Market analysis shows growing investment in {query}..."
    )


@tool
def wikipedia_lookup(topic: str) -> str:
    """Look up background information on Wikipedia."""
    return (
        f"Wikipedia: {topic}\n"
        f"{topic} is a field of study that encompasses multiple disciplines. "
        f"It has roots dating back to the early 2000s and has seen rapid growth "
        f"in recent years."
    )


@tool
def calculator(expression: str) -> str:
    """Evaluate a mathematical expression."""
    try:
        result = eval(expression, {"__builtins__": {}})  # noqa: S307
        return str(result)
    except Exception as e:
        return f"Error: {e}"


@tool
def code_interpreter(code: str) -> str:
    """Run a Python code snippet and return the output."""
    return f"Code output:\n>>> {code}\n(simulated output for demo)"


@tool
def format_report(title: str, sections: str) -> str:
    """Format a structured report with title and sections."""
    return f"# {title}\n\n{sections}\n\n---\nGenerated by DuraLang."


# ── Agent: Researcher ────────────────────────────────────────────────────────

research_tools = [web_search, wikipedia_lookup]
research_tools_by_name = {t.name: t for t in research_tools}


@dura
async def researcher(topic: str) -> str:
    """Research agent — gathers information using web search and wikipedia."""
    llm = ChatAnthropic(model="claude-sonnet-4-6")
    llm_with_tools = llm.bind_tools(research_tools)

    messages = [
        SystemMessage(
            content=(
                "You are a research agent. Use web_search for current information "
                "and wikipedia_lookup for background context. Gather comprehensive "
                "information on the topic. Call BOTH tools to get a full picture."
            )
        ),
        HumanMessage(content=f"Research this topic thoroughly: {topic}"),
    ]

    for _ in range(10):
        response = await llm_with_tools.ainvoke(messages)
        messages.append(response)
        if not response.tool_calls:
            break
        for tc in response.tool_calls:
            result = await research_tools_by_name[tc["name"]].ainvoke(tc["args"])
            messages.append(ToolMessage(content=str(result), tool_call_id=tc["id"]))

    return response.content


# ── Agent: Analyst ────────────────────────────────────────────────────────────

analysis_tools = [calculator, code_interpreter]
analysis_tools_by_name = {t.name: t for t in analysis_tools}


@dura
async def analyst(research_findings: str, question: str) -> str:
    """Analysis agent — processes research with calculations and code."""
    llm = ChatAnthropic(model="claude-sonnet-4-6")
    llm_with_tools = llm.bind_tools(analysis_tools)

    messages = [
        SystemMessage(
            content=(
                "You are an analyst. Given research findings, perform quantitative "
                "analysis using the calculator and code_interpreter tools. "
                "Extract key metrics, compute growth rates, and identify trends."
            )
        ),
        HumanMessage(
            content=(
                f"Research findings:\n{research_findings}\n\n"
                f"Analysis question: {question}"
            )
        ),
    ]

    for _ in range(10):
        response = await llm_with_tools.ainvoke(messages)
        messages.append(response)
        if not response.tool_calls:
            break
        for tc in response.tool_calls:
            result = await analysis_tools_by_name[tc["name"]].ainvoke(tc["args"])
            messages.append(ToolMessage(content=str(result), tool_call_id=tc["id"]))

    return response.content


# ── Agent: Writer ─────────────────────────────────────────────────────────────

writer_tools = [format_report]
writer_tools_by_name = {t.name: t for t in writer_tools}


@dura
async def writer(research: str, analysis: str, topic: str) -> str:
    """Writer agent — combines research and analysis into a formatted report."""
    llm = ChatAnthropic(model="claude-sonnet-4-6")
    llm_with_tools = llm.bind_tools(writer_tools)

    messages = [
        SystemMessage(
            content=(
                "You are a technical writer. Combine the research findings and "
                "analysis into a clear, well-structured report. Use the "
                "format_report tool to produce the final output."
            )
        ),
        HumanMessage(
            content=(
                f"Topic: {topic}\n\n"
                f"Research findings:\n{research}\n\n"
                f"Analysis:\n{analysis}\n\n"
                f"Write a comprehensive report combining these inputs."
            )
        ),
    ]

    for _ in range(10):
        response = await llm_with_tools.ainvoke(messages)
        messages.append(response)
        if not response.tool_calls:
            break
        for tc in response.tool_calls:
            result = await writer_tools_by_name[tc["name"]].ainvoke(tc["args"])
            messages.append(ToolMessage(content=str(result), tool_call_id=tc["id"]))

    return response.content


# ── Pipeline agent — fixed sequence: research → analyze → write ──────────────


@dura
async def pipeline_agent(topic: str) -> str:
    """Agent that runs a fixed research pipeline.

    Each sub-agent call becomes a Temporal Child Workflow with its own
    event history. If any step fails, only that step retries.
    """
    # Step 1: Research
    research_findings = await researcher(topic)

    # Step 2: Analyze
    analysis_results = await analyst(
        research_findings=research_findings,
        question=f"What are the key quantitative trends in {topic}?",
    )

    # Step 3: Write
    final_report = await writer(
        research=research_findings,
        analysis=analysis_results,
        topic=topic,
    )

    return final_report


# ── Run ───────────────────────────────────────────────────────────────────────


async def main():
    print("\nStarting multi-agent pipeline...\n")
    print("  pipeline_agent -> researcher -> analyst -> writer\n")
    report = await pipeline_agent("The impact of AI agents on software engineering")
    print("\n" + "=" * 60)
    print("FINAL REPORT")
    print("=" * 60)
    print(report)
    print("=" * 60)


if __name__ == "__main__":
    asyncio.run(main())
