"""Multi-agent research system — multiple tools, multiple @dura agents.

Architecture:
    orchestrator (top-level @dura)
    ├── researcher    (@dura child workflow — web search + wikipedia)
    ├── analyst       (@dura child workflow — calculator + code interpreter)
    └── writer        (@dura child workflow — summarizes everything)

Each agent has its own tools, its own LLM calls, and its own Temporal event history.
The orchestrator coordinates them as Temporal Child Workflows.
"""

import asyncio

from langchain_anthropic import ChatAnthropic
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage, ToolMessage
from langchain_core.tools import tool

from duralang import dura

# ── Tools ────────────────────────────────────────────────────────────────────


@tool
def web_search(query: str) -> str:
    """Search the web for current information."""
    # In production, this would call Tavily, Brave, etc.
    return (
        f"Search results for '{query}':\n"
        f"1. Recent advances in {query} show significant progress...\n"
        f"2. Experts predict major breakthroughs in {query} by 2027...\n"
        f"3. Market analysis shows growing investment in {query}..."
    )


@tool
def wikipedia_lookup(topic: str) -> str:
    """Look up background information on Wikipedia."""
    return (
        f"Wikipedia: {topic}\n"
        f"{topic} is a field of study that encompasses multiple disciplines. "
        f"It has roots dating back to the early 2000s and has seen rapid growth "
        f"in recent years. Key contributors include leading research labs and "
        f"universities worldwide."
    )


@tool
def calculator(expression: str) -> str:
    """Evaluate a mathematical expression."""
    try:
        result = eval(expression, {"__builtins__": {}})  # noqa: S307
        return str(result)
    except Exception as e:
        return f"Error: {e}"


@tool
def code_interpreter(code: str) -> str:
    """Run a Python code snippet and return the output."""
    # In production, this would run in a sandbox
    return f"Code output:\n>>> {code}\n(simulated output for demo)"


@tool
def format_report(title: str, sections: str) -> str:
    """Format a structured report with title and sections."""
    return f"# {title}\n\n{sections}\n\n---\nGenerated by DuraLang multi-agent system."


# ── Agent: Researcher ────────────────────────────────────────────────────────

research_tools = [web_search, wikipedia_lookup]
research_tools_by_name = {t.name: t for t in research_tools}


@dura
async def researcher(topic: str) -> str:
    """Research agent — gathers information using web search and wikipedia.

    Has access to: web_search, wikipedia_lookup
    Returns: research findings as text
    """
    llm = ChatAnthropic(model="claude-sonnet-4-6")
    llm_with_tools = llm.bind_tools(research_tools)

    messages = [
        SystemMessage(
            content=(
                "You are a research agent. Use web_search for current information "
                "and wikipedia_lookup for background context. Gather comprehensive "
                "information on the topic. Call BOTH tools to get a full picture."
            )
        ),
        HumanMessage(content=f"Research this topic thoroughly: {topic}"),
    ]

    while True:
        response = await llm_with_tools.ainvoke(messages)
        messages.append(response)

        if not response.tool_calls:
            break

        # Execute all tool calls (may be parallel if LLM requests multiple)
        for tc in response.tool_calls:
            result = await research_tools_by_name[tc["name"]].ainvoke(tc["args"])
            messages.append(
                ToolMessage(content=str(result), tool_call_id=tc["id"])
            )

    return response.content


# ── Agent: Analyst ────────────────────────────────────────────────────────────

analysis_tools = [calculator, code_interpreter]
analysis_tools_by_name = {t.name: t for t in analysis_tools}


@dura
async def analyst(research_findings: str, question: str) -> str:
    """Analysis agent — processes research with calculations and code.

    Has access to: calculator, code_interpreter
    Returns: analytical insights as text
    """
    llm = ChatAnthropic(model="claude-sonnet-4-6")
    llm_with_tools = llm.bind_tools(analysis_tools)

    messages = [
        SystemMessage(
            content=(
                "You are an analyst. Given research findings, perform quantitative "
                "analysis using the calculator and code_interpreter tools. "
                "Extract key metrics, compute growth rates, and identify trends."
            )
        ),
        HumanMessage(
            content=(
                f"Research findings:\n{research_findings}\n\n"
                f"Analysis question: {question}"
            )
        ),
    ]

    while True:
        response = await llm_with_tools.ainvoke(messages)
        messages.append(response)

        if not response.tool_calls:
            break

        for tc in response.tool_calls:
            result = await analysis_tools_by_name[tc["name"]].ainvoke(tc["args"])
            messages.append(
                ToolMessage(content=str(result), tool_call_id=tc["id"])
            )

    return response.content


# ── Agent: Writer ─────────────────────────────────────────────────────────────

writer_tools = [format_report]
writer_tools_by_name = {t.name: t for t in writer_tools}


@dura
async def writer(research: str, analysis: str, topic: str) -> str:
    """Writer agent — combines research and analysis into a formatted report.

    Has access to: format_report
    Returns: final formatted report
    """
    llm = ChatAnthropic(model="claude-sonnet-4-6")
    llm_with_tools = llm.bind_tools(writer_tools)

    messages = [
        SystemMessage(
            content=(
                "You are a technical writer. Combine the research findings and "
                "analysis into a clear, well-structured report. Use the "
                "format_report tool to produce the final output."
            )
        ),
        HumanMessage(
            content=(
                f"Topic: {topic}\n\n"
                f"Research findings:\n{research}\n\n"
                f"Analysis:\n{analysis}\n\n"
                f"Write a comprehensive report combining these inputs."
            )
        ),
    ]

    while True:
        response = await llm_with_tools.ainvoke(messages)
        messages.append(response)

        if not response.tool_calls:
            break

        for tc in response.tool_calls:
            result = await writer_tools_by_name[tc["name"]].ainvoke(tc["args"])
            messages.append(
                ToolMessage(content=str(result), tool_call_id=tc["id"])
            )

    return response.content


# ── Orchestrator ──────────────────────────────────────────────────────────────


@dura
async def orchestrator(topic: str) -> str:
    """Top-level orchestrator — coordinates researcher, analyst, and writer.

    Each sub-agent call becomes a Temporal Child Workflow:

        orchestrator (workflow)
        ├── researcher (child workflow)
        │   ├── dura__llm (activity)
        │   ├── dura__tool: web_search (activity)
        │   ├── dura__tool: wikipedia_lookup (activity)
        │   └── dura__llm (activity)
        ├── analyst (child workflow)
        │   ├── dura__llm (activity)
        │   ├── dura__tool: calculator (activity)
        │   ├── dura__tool: code_interpreter (activity)
        │   └── dura__llm (activity)
        └── writer (child workflow)
            ├── dura__llm (activity)
            ├── dura__tool: format_report (activity)
            └── dura__llm (activity)
    """
    # Step 1: Research — calls web_search and wikipedia_lookup
    # This becomes a Temporal Child Workflow automatically
    research_findings = await researcher(topic)

    # Step 2: Analyze — calls calculator and code_interpreter
    # Another Child Workflow, with its own retries and event history
    analysis_results = await analyst(
        research_findings=research_findings,
        question=f"What are the key quantitative trends in {topic}?",
    )

    # Step 3: Write — calls format_report
    # Third Child Workflow
    final_report = await writer(
        research=research_findings,
        analysis=analysis_results,
        topic=topic,
    )

    return final_report


# ── Run ───────────────────────────────────────────────────────────────────────


async def main():
    """Run the multi-agent system.

    What happens under the hood:
    1. orchestrator() starts as a top-level Temporal Workflow
    2. researcher() starts as a Child Workflow
       - LLM calls → dura__llm activities (with retry + heartbeat)
       - web_search → dura__tool activity
       - wikipedia_lookup → dura__tool activity
    3. analyst() starts as a Child Workflow
       - LLM calls → dura__llm activities
       - calculator → dura__tool activity
       - code_interpreter → dura__tool activity
    4. writer() starts as a Child Workflow
       - LLM calls → dura__llm activities
       - format_report → dura__tool activity
    5. orchestrator returns the final report

    If any step fails, Temporal retries it. If the worker crashes,
    Temporal replays from the last completed step. Nothing is lost.
    """
    print("\n🚀 Starting multi-agent orchestrator...\n")
    print("  orchestrator → researcher → analyst → writer\n")
    report = await orchestrator("The impact of AI agents on software engineering")
    print("\n" + "=" * 60)
    print("FINAL REPORT")
    print("=" * 60)
    print(report)
    print("=" * 60)


if __name__ == "__main__":
    asyncio.run(main())
