"""Multi-agent research system — multiple tools, multiple @dura agents.

This example shows a fixed pipeline: research → analyze → write.
Each step is a @dura agent with its own tools and Temporal event history.

For an example where the LLM decides which agents to call dynamically,
see multiagent_system.py.
"""

import asyncio

from langchain.agents import create_agent
from langchain_core.messages import HumanMessage
from langchain_core.tools import tool

from duralang import dura

# ── Tools ────────────────────────────────────────────────────────────────────


@tool
def web_search(query: str) -> str:
    """Search the web for current information."""
    return (
        f"Search results for '{query}':\n"
        f"1. Recent advances in {query} show significant progress...\n"
        f"2. Experts predict major breakthroughs in {query} by 2027...\n"
        f"3. Market analysis shows growing investment in {query}..."
    )


@tool
def wikipedia_lookup(topic: str) -> str:
    """Look up background information on Wikipedia."""
    return (
        f"Wikipedia: {topic}\n"
        f"{topic} is a field of study that encompasses multiple disciplines. "
        f"It has roots dating back to the early 2000s and has seen rapid growth "
        f"in recent years."
    )


@tool
def calculator(expression: str) -> str:
    """Evaluate a mathematical expression."""
    try:
        result = eval(expression, {"__builtins__": {}})  # noqa: S307
        return str(result)
    except Exception as e:
        return f"Error: {e}"


@tool
def code_interpreter(code: str) -> str:
    """Run a Python code snippet and return the output."""
    return f"Code output:\n>>> {code}\n(simulated output for demo)"


@tool
def format_report(title: str, sections: str) -> str:
    """Format a structured report with title and sections."""
    return f"# {title}\n\n{sections}\n\n---\nGenerated by DuraLang."


# ── Agent: Researcher ────────────────────────────────────────────────────────


@dura
async def researcher(topic: str) -> str:
    """Research agent — gathers information using web search and wikipedia."""
    agent = create_agent(
        model="claude-sonnet-4-6",
        tools=[web_search, wikipedia_lookup],
        system_prompt=(
            "You are a research agent. Use web_search for current information "
            "and wikipedia_lookup for background context. Gather comprehensive "
            "information on the topic. Call BOTH tools to get a full picture."
        ),
    )
    result = await agent.ainvoke(
        {"messages": [HumanMessage(content=f"Research this topic thoroughly: {topic}")]}
    )
    return result["messages"][-1].content


# ── Agent: Analyst ────────────────────────────────────────────────────────────


@dura
async def analyst(research_findings: str, question: str) -> str:
    """Analysis agent — processes research with calculations and code."""
    agent = create_agent(
        model="claude-sonnet-4-6",
        tools=[calculator, code_interpreter],
        system_prompt=(
            "You are an analyst. Given research findings, perform quantitative "
            "analysis using the calculator and code_interpreter tools. "
            "Extract key metrics, compute growth rates, and identify trends."
        ),
    )
    result = await agent.ainvoke(
        {"messages": [HumanMessage(content=(
            f"Research findings:\n{research_findings}\n\n"
            f"Analysis question: {question}"
        ))]}
    )
    return result["messages"][-1].content


# ── Agent: Writer ─────────────────────────────────────────────────────────────


@dura
async def writer(research: str, analysis: str, topic: str) -> str:
    """Writer agent — combines research and analysis into a formatted report."""
    agent = create_agent(
        model="claude-sonnet-4-6",
        tools=[format_report],
        system_prompt=(
            "You are a technical writer. Combine the research findings and "
            "analysis into a clear, well-structured report. Use the "
            "format_report tool to produce the final output."
        ),
    )
    result = await agent.ainvoke(
        {"messages": [HumanMessage(content=(
            f"Topic: {topic}\n\n"
            f"Research findings:\n{research}\n\n"
            f"Analysis:\n{analysis}\n\n"
            f"Write a comprehensive report combining these inputs."
        ))]}
    )
    return result["messages"][-1].content


# ── Pipeline agent — fixed sequence: research → analyze → write ──────────────


@dura
async def pipeline_agent(topic: str) -> str:
    """Agent that runs a fixed research pipeline.

    Each sub-agent call becomes a Temporal Child Workflow with its own
    event history. If any step fails, only that step retries.
    """
    # Step 1: Research
    research_findings = await researcher(topic)

    # Step 2: Analyze
    analysis_results = await analyst(
        research_findings=research_findings,
        question=f"What are the key quantitative trends in {topic}?",
    )

    # Step 3: Write
    final_report = await writer(
        research=research_findings,
        analysis=analysis_results,
        topic=topic,
    )

    return final_report


# ── Run ───────────────────────────────────────────────────────────────────────


async def main():
    print("\nStarting multi-agent pipeline...\n")
    print("  pipeline_agent -> researcher -> analyst -> writer\n")
    report = await pipeline_agent("The impact of AI agents on software engineering")
    print("\n" + "=" * 60)
    print("FINAL REPORT")
    print("=" * 60)
    print(report)
    print("=" * 60)


if __name__ == "__main__":
    asyncio.run(main())
