"""Multi-agent with mixed tools — the LLM decides everything.

This example shows DuraLang's full power: an agent that has both sub-agents
and regular tools available. The LLM freely decides:
  - Which agent or tool to call
  - How many times to call each
  - What order to call them in
  - When it has enough information to respond

Each sub-agent has its own tools and its own agent loop. Under the hood:
  - Regular @tool calls → Temporal Activity (single retryable operation)
  - dura_agent_tool() calls → Temporal Child Workflow (own event history)
  - LLM calls → Temporal Activity (retried, heartbeated)

The dispatch loop is identical for all tool types — DuraLang routes
each call to the right Temporal primitive automatically.
"""

import asyncio

from langchain_anthropic import ChatAnthropic
from langchain_core.messages import HumanMessage, SystemMessage, ToolMessage
from langchain_core.tools import tool

from duralang import dura, dura_agent_tool

# ── Regular tools ────────────────────────────────────────────────────────────


@tool
def web_search(query: str) -> str:
    """Search the web for current information on a topic."""
    return (
        f"Search results for '{query}':\n"
        f"1. Recent studies show significant developments in {query}.\n"
        f"2. Industry experts predict major shifts in {query} by 2027.\n"
        f"3. Investment in {query} grew 40% year-over-year."
    )


@tool
def wikipedia_lookup(topic: str) -> str:
    """Look up background and historical information on Wikipedia."""
    return (
        f"Wikipedia: {topic}\n"
        f"{topic} has roots in early computing research. The field has evolved "
        f"through several paradigm shifts. Current approaches emphasize "
        f"scalability, reliability, and autonomous operation."
    )


@tool
def calculator(expression: str) -> str:
    """Evaluate a mathematical expression. Use for quantitative analysis."""
    try:
        result = eval(expression, {"__builtins__": {}})  # noqa: S307
        return f"{expression} = {result}"
    except Exception as e:
        return f"Error evaluating '{expression}': {e}"


@tool
def format_document(title: str, body: str) -> str:
    """Format text into a clean document with title and body."""
    return f"# {title}\n\n{body}\n\n---\nGenerated by DuraLang."


# ── Sub-agents (each becomes a Child Workflow when called) ───────────────────

research_tools = [web_search, wikipedia_lookup]
research_tools_by_name = {t.name: t for t in research_tools}


@dura
async def researcher(query: str) -> str:
    """Research agent — gathers information via web search and wikipedia."""
    llm = ChatAnthropic(model="claude-sonnet-4-6")
    llm_with_tools = llm.bind_tools(research_tools)

    messages = [
        SystemMessage(
            content=(
                "You are a research agent. Use web_search for current info and "
                "wikipedia_lookup for background. Gather what's needed to answer "
                "the query, then return a clear summary. Be concise."
            )
        ),
        HumanMessage(content=query),
    ]

    for _ in range(10):
        response = await llm_with_tools.ainvoke(messages)
        messages.append(response)
        if not response.tool_calls:
            break
        for tc in response.tool_calls:
            result = await research_tools_by_name[tc["name"]].ainvoke(tc["args"])
            messages.append(ToolMessage(content=str(result), tool_call_id=tc["id"]))

    return response.content


analysis_tools = [calculator]
analysis_tools_by_name = {t.name: t for t in analysis_tools}


@dura
async def analyst(data: str, question: str) -> str:
    """Analysis agent — analyzes data with calculations and trend identification."""
    llm = ChatAnthropic(model="claude-sonnet-4-6")
    llm_with_tools = llm.bind_tools(analysis_tools)

    messages = [
        SystemMessage(
            content=(
                "You are an analyst. Given data and a question, provide quantitative "
                "and qualitative analysis. Use the calculator for any math. Be concise."
            )
        ),
        HumanMessage(content=f"Data:\n{data}\n\nQuestion: {question}"),
    ]

    for _ in range(10):
        response = await llm_with_tools.ainvoke(messages)
        messages.append(response)
        if not response.tool_calls:
            break
        for tc in response.tool_calls:
            result = await analysis_tools_by_name[tc["name"]].ainvoke(tc["args"])
            messages.append(ToolMessage(content=str(result), tool_call_id=tc["id"]))

    return response.content


writer_tools = [format_document]
writer_tools_by_name = {t.name: t for t in writer_tools}


@dura
async def writer(content: str, instructions: str) -> str:
    """Writer agent — produces formatted, polished documents."""
    llm = ChatAnthropic(model="claude-sonnet-4-6")
    llm_with_tools = llm.bind_tools(writer_tools)

    messages = [
        SystemMessage(
            content=(
                "You are a writer. Take the provided content and instructions, "
                "then produce a well-written output. Use format_document to "
                "create a clean final document. Be concise."
            )
        ),
        HumanMessage(
            content=f"Content:\n{content}\n\nInstructions: {instructions}"
        ),
    ]

    for _ in range(10):
        response = await llm_with_tools.ainvoke(messages)
        messages.append(response)
        if not response.tool_calls:
            break
        for tc in response.tool_calls:
            result = await writer_tools_by_name[tc["name"]].ainvoke(tc["args"])
            messages.append(ToolMessage(content=str(result), tool_call_id=tc["id"]))

    return response.content


# ── Orchestrator — sub-agents and regular tools in one list ───────────────────

all_tools = [
    dura_agent_tool(researcher),       # → Temporal Child Workflow
    dura_agent_tool(analyst),          # → Temporal Child Workflow
    dura_agent_tool(writer),           # → Temporal Child Workflow
    calculator,                         # → Temporal Activity
]
tools_by_name = {t.name: t for t in all_tools}


@dura
async def orchestrator(task: str) -> str:
    """Stochastic orchestrator — the LLM decides which agents and tools to call.

    The execution path is different every run. But every operation is
    individually durable: LLM calls, tool calls, and agent calls are all
    Temporal Activities or Child Workflows with automatic retry.
    """
    llm = ChatAnthropic(model="claude-sonnet-4-6")
    llm_with_tools = llm.bind_tools(all_tools)

    messages = [
        SystemMessage(
            content=(
                "You have access to specialist agents and tools:\n"
                "- call_researcher: gathers information (web search, wikipedia)\n"
                "- call_analyst: analyzes data (calculations, trends)\n"
                "- call_writer: produces formatted documents\n"
                "- calculator: evaluate math expressions directly\n\n"
                "Use them in whatever order makes sense. Call agents multiple "
                "times if needed. When you have enough, give your final answer."
            )
        ),
        HumanMessage(content=task),
    ]

    for i in range(20):
        response = await llm_with_tools.ainvoke(messages)
        messages.append(response)

        if not response.tool_calls:
            break

        for tc in response.tool_calls:
            print(f"  → Calling: {tc['name']}")
            # Same ainvoke() for both sub-agents and regular tools
            result = await tools_by_name[tc["name"]].ainvoke(tc["args"])
            messages.append(
                ToolMessage(content=str(result), tool_call_id=tc["id"])
            )

    return response.content


# ── Run ──────────────────────────────────────────────────────────────────────


async def main():
    print()
    print("=" * 60)
    print("STOCHASTIC ORCHESTRATION")
    print("The LLM decides which agents and tools to call.")
    print("Every run may take a different path.")
    print("=" * 60)
    print()

    result = await orchestrator(
        "Research the current state of AI agents in software engineering. "
        "Analyze the growth trends. Write a brief report."
    )

    print()
    print("=" * 60)
    print("FINAL OUTPUT")
    print("=" * 60)
    print(result)
    print("=" * 60)


if __name__ == "__main__":
    asyncio.run(main())
