"""Multi-agent with mixed tools — the LLM decides everything.

This example shows DuraLang's full power: an orchestrator agent that has both
sub-agents and regular tools available. The LLM freely decides:
  - Which agent or tool to call
  - How many times to call each
  - What order to call them in
  - When it has enough information to respond

Each sub-agent has its own tools and its own agent loop. Under the hood:
  - Regular @tool calls → Temporal Activity (single retryable operation)
  - dura_agent_tool() calls → Temporal Child Workflow (own event history)
  - LLM calls → Temporal Activity (retried, heartbeated)
"""

import asyncio

from langchain.agents import create_agent
from langchain_core.messages import HumanMessage
from langchain_core.tools import tool

from duralang import dura, dura_agent_tool

# ── Regular tools ────────────────────────────────────────────────────────────


@tool
def web_search(query: str) -> str:
    """Search the web for current information on a topic."""
    return (
        f"Search results for '{query}':\n"
        f"1. Recent studies show significant developments in {query}.\n"
        f"2. Industry experts predict major shifts in {query} by 2027.\n"
        f"3. Investment in {query} grew 40% year-over-year."
    )


@tool
def wikipedia_lookup(topic: str) -> str:
    """Look up background and historical information on Wikipedia."""
    return (
        f"Wikipedia: {topic}\n"
        f"{topic} has roots in early computing research. The field has evolved "
        f"through several paradigm shifts. Current approaches emphasize "
        f"scalability, reliability, and autonomous operation."
    )


@tool
def calculator(expression: str) -> str:
    """Evaluate a mathematical expression. Use for quantitative analysis."""
    try:
        result = eval(expression, {"__builtins__": {}})  # noqa: S307
        return f"{expression} = {result}"
    except Exception as e:
        return f"Error evaluating '{expression}': {e}"


@tool
def format_document(title: str, body: str) -> str:
    """Format text into a clean document with title and body."""
    return f"# {title}\n\n{body}\n\n---\nGenerated by DuraLang."


# ── Sub-agents (each becomes a Child Workflow when called) ───────────────────


@dura
async def researcher(query: str) -> str:
    """Research agent — gathers information via web search and wikipedia."""
    agent = create_agent(
        model="claude-sonnet-4-6",
        tools=[web_search, wikipedia_lookup],
        system_prompt=(
            "You are a research agent. Use web_search for current info and "
            "wikipedia_lookup for background. Gather what's needed to answer "
            "the query, then return a clear summary. Be concise."
        ),
    )
    result = await agent.ainvoke({"messages": [HumanMessage(content=query)]})
    return result["messages"][-1].content


@dura
async def analyst(data: str, question: str) -> str:
    """Analysis agent — analyzes data with calculations and trend identification."""
    agent = create_agent(
        model="claude-sonnet-4-6",
        tools=[calculator],
        system_prompt=(
            "You are an analyst. Given data and a question, provide quantitative "
            "and qualitative analysis. Use the calculator for any math. Be concise."
        ),
    )
    result = await agent.ainvoke(
        {"messages": [HumanMessage(content=f"Data:\n{data}\n\nQuestion: {question}")]}
    )
    return result["messages"][-1].content


@dura
async def writer(content: str, instructions: str) -> str:
    """Writer agent — produces formatted, polished documents."""
    agent = create_agent(
        model="claude-sonnet-4-6",
        tools=[format_document],
        system_prompt=(
            "You are a writer. Take the provided content and instructions, "
            "then produce a well-written output. Use format_document to "
            "create a clean final document. Be concise."
        ),
    )
    result = await agent.ainvoke(
        {"messages": [HumanMessage(content=f"Content:\n{content}\n\nInstructions: {instructions}")]}
    )
    return result["messages"][-1].content


# ── Orchestrator — sub-agents and regular tools in one list ───────────────────

all_tools = [
    dura_agent_tool(researcher),       # → Temporal Child Workflow
    dura_agent_tool(analyst),          # → Temporal Child Workflow
    dura_agent_tool(writer),           # → Temporal Child Workflow
    calculator,                         # → Temporal Activity
]


@dura
async def orchestrator(task: str) -> str:
    """Stochastic orchestrator — the LLM decides which agents and tools to call.

    The execution path is different every run. But every operation is
    individually durable: LLM calls, tool calls, and agent calls are all
    Temporal Activities or Child Workflows with automatic retry.
    """
    agent = create_agent(
        model="claude-sonnet-4-6",
        tools=all_tools,
        system_prompt=(
            "You have access to specialist agents and tools:\n"
            "- call_researcher: gathers information (web search, wikipedia)\n"
            "- call_analyst: analyzes data (calculations, trends)\n"
            "- call_writer: produces formatted documents\n"
            "- calculator: evaluate math expressions directly\n\n"
            "Use them in whatever order makes sense. Call agents multiple "
            "times if needed. When you have enough, give your final answer."
        ),
    )
    result = await agent.ainvoke({"messages": [HumanMessage(content=task)]})
    return result["messages"][-1].content


# ── Run ──────────────────────────────────────────────────────────────────────


async def main():
    print()
    print("=" * 60)
    print("STOCHASTIC ORCHESTRATION")
    print("The LLM decides which agents and tools to call.")
    print("Every run may take a different path.")
    print("=" * 60)
    print()

    result = await orchestrator(
        "Research the current state of AI agents in software engineering. "
        "Analyze the growth trends. Write a brief report."
    )

    print()
    print("=" * 60)
    print("FINAL OUTPUT")
    print("=" * 60)
    print(result)
    print("=" * 60)


if __name__ == "__main__":
    asyncio.run(main())
