"""Fully stochastic multi-agent system — the LLM decides everything.

This is the example that proves DuraLang's value proposition.

The orchestrator LLM has tool schemas for three sub-agents. It freely decides:
  - Which agent to call
  - How many times to call each agent
  - What order to call them in
  - Whether to call the same agent again with refined questions
  - When it has enough information to respond

Each sub-agent also has its own tools and its own agent loop — the LLM
inside each sub-agent decides which tools to use and how many times to loop.

Agent-to-agent calls are routed as Temporal Child Workflows (not activities),
so there are no timeout issues and each agent gets its own event history.

This is impossible to express as a graph. The execution path is completely
determined at runtime by LLM outputs. But every single operation — every
LLM call, tool call, and agent call — is individually durable via Temporal.
"""

import asyncio
import json

from langchain_anthropic import ChatAnthropic
from langchain_core.messages import HumanMessage, SystemMessage, ToolMessage
from langchain_core.tools import tool

from duralang import dura

# ── Sub-agent tools ──────────────────────────────────────────────────────────


@tool
def web_search(query: str) -> str:
    """Search the web for current information on a topic."""
    return (
        f"Search results for '{query}':\n"
        f"1. Recent studies show significant developments in {query}.\n"
        f"2. Industry experts predict major shifts in {query} by 2027.\n"
        f"3. Investment in {query} grew 40% year-over-year."
    )


@tool
def wikipedia_lookup(topic: str) -> str:
    """Look up background and historical information on Wikipedia."""
    return (
        f"Wikipedia: {topic}\n"
        f"{topic} has roots in early computing research. The field has evolved "
        f"through several paradigm shifts. Current approaches emphasize "
        f"scalability, reliability, and autonomous operation."
    )


@tool
def calculator(expression: str) -> str:
    """Evaluate a mathematical expression. Use for quantitative analysis."""
    try:
        result = eval(expression, {"__builtins__": {}})  # noqa: S307
        return f"{expression} = {result}"
    except Exception as e:
        return f"Error evaluating '{expression}': {e}"


@tool
def format_document(title: str, body: str) -> str:
    """Format text into a clean document with title and body."""
    return f"# {title}\n\n{body}\n\n---\nGenerated by DuraLang stochastic agent system."


# ── Sub-agents (each is a @dura child workflow) ─────────────────────────────

research_tools = [web_search, wikipedia_lookup]
research_tools_by_name = {t.name: t for t in research_tools}


@dura
async def researcher(query: str) -> str:
    """Research agent with web search and wikipedia tools."""
    llm = ChatAnthropic(model="claude-sonnet-4-6")
    llm_with_tools = llm.bind_tools(research_tools)

    messages = [
        SystemMessage(
            content=(
                "You are a research agent. Use web_search for current info and "
                "wikipedia_lookup for background. Gather what's needed to answer "
                "the query, then return a clear summary. Be concise."
            )
        ),
        HumanMessage(content=query),
    ]

    for _ in range(10):
        response = await llm_with_tools.ainvoke(messages)
        messages.append(response)
        if not response.tool_calls:
            break
        for tc in response.tool_calls:
            result = await research_tools_by_name[tc["name"]].ainvoke(tc["args"])
            messages.append(ToolMessage(content=str(result), tool_call_id=tc["id"]))

    return response.content


analysis_tools = [calculator]
analysis_tools_by_name = {t.name: t for t in analysis_tools}


@dura
async def analyst(data: str, question: str) -> str:
    """Analysis agent with calculator tool."""
    llm = ChatAnthropic(model="claude-sonnet-4-6")
    llm_with_tools = llm.bind_tools(analysis_tools)

    messages = [
        SystemMessage(
            content=(
                "You are an analyst. Given data and a question, provide quantitative "
                "and qualitative analysis. Use the calculator for any math. Be concise."
            )
        ),
        HumanMessage(content=f"Data:\n{data}\n\nQuestion: {question}"),
    ]

    for _ in range(10):
        response = await llm_with_tools.ainvoke(messages)
        messages.append(response)
        if not response.tool_calls:
            break
        for tc in response.tool_calls:
            result = await analysis_tools_by_name[tc["name"]].ainvoke(tc["args"])
            messages.append(ToolMessage(content=str(result), tool_call_id=tc["id"]))

    return response.content


writer_tools = [format_document]
writer_tools_by_name = {t.name: t for t in writer_tools}


@dura
async def writer(content: str, instructions: str) -> str:
    """Writer agent with document formatting tool."""
    llm = ChatAnthropic(model="claude-sonnet-4-6")
    llm_with_tools = llm.bind_tools(writer_tools)

    messages = [
        SystemMessage(
            content=(
                "You are a writer. Take the provided content and instructions, "
                "then produce a well-written output. Use format_document to "
                "create a clean final document. Be concise."
            )
        ),
        HumanMessage(
            content=f"Content:\n{content}\n\nInstructions: {instructions}"
        ),
    ]

    for _ in range(10):
        response = await llm_with_tools.ainvoke(messages)
        messages.append(response)
        if not response.tool_calls:
            break
        for tc in response.tool_calls:
            result = await writer_tools_by_name[tc["name"]].ainvoke(tc["args"])
            messages.append(ToolMessage(content=str(result), tool_call_id=tc["id"]))

    return response.content


# ── Agent tool schemas (given to the LLM so it can choose which to call) ─────

AGENT_TOOL_SCHEMAS = [
    {
        "name": "call_researcher",
        "description": (
            "Call the research agent to gather information on a topic. "
            "Use this when you need current information, background context, "
            "or factual data about something."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "The research query",
                }
            },
            "required": ["query"],
        },
    },
    {
        "name": "call_analyst",
        "description": (
            "Call the analysis agent to analyze data and answer quantitative questions. "
            "Use this when you have data that needs analysis, calculations, "
            "or trend identification."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string",
                    "description": "The data to analyze",
                },
                "question": {
                    "type": "string",
                    "description": "The analysis question",
                },
            },
            "required": ["data", "question"],
        },
    },
    {
        "name": "call_writer",
        "description": (
            "Call the writer agent to produce a formatted document. "
            "Use this when you have gathered enough information and analysis "
            "and want to produce a final polished output."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "description": "The content to format",
                },
                "instructions": {
                    "type": "string",
                    "description": "How to format/write the content",
                },
            },
            "required": ["content", "instructions"],
        },
    },
]

# Map tool names to @dura functions — called directly from the orchestrator's
# workflow context, so they become Temporal Child Workflows (not activities).
AGENT_DISPATCH = {
    "call_researcher": lambda args: researcher(args["query"]),
    "call_analyst": lambda args: analyst(args["data"], args["question"]),
    "call_writer": lambda args: writer(args["content"], args["instructions"]),
}


# ── Orchestrator — LLM decides everything ────────────────────────────────────


@dura
async def orchestrator(task: str) -> str:
    """Fully stochastic orchestrator — the LLM decides which agents to call and when.

    Agent tool calls are dispatched as Child Workflows directly from
    the workflow context. The LLM freely chooses which agents to call,
    in what order, and how many times.
    """
    llm = ChatAnthropic(model="claude-sonnet-4-6")
    llm_with_tools = llm.bind_tools(AGENT_TOOL_SCHEMAS)

    messages = [
        SystemMessage(
            content=(
                "You are an orchestrator with access to three specialist agents:\n"
                "- call_researcher: gathers information (web search, wikipedia)\n"
                "- call_analyst: analyzes data (calculations, trends)\n"
                "- call_writer: produces formatted documents\n\n"
                "You decide which agents to call, in what order, and how many times. "
                "You can call the same agent multiple times with different queries. "
                "You can call agents in whatever order makes sense for the task.\n\n"
                "When you have enough information, provide your final answer directly."
            )
        ),
        HumanMessage(content=task),
    ]

    for i in range(20):  # safety limit
        response = await llm_with_tools.ainvoke(messages)
        messages.append(response)

        if not response.tool_calls:
            break

        for tc in response.tool_calls:
            agent_name = tc["name"]
            print(f"  → Orchestrator calling: {agent_name}")

            # Dispatch directly as a child workflow (not through dura__tool activity)
            dispatch_fn = AGENT_DISPATCH.get(agent_name)
            if dispatch_fn:
                result = await dispatch_fn(tc["args"])
            else:
                result = f"Unknown agent: {agent_name}"

            messages.append(
                ToolMessage(content=str(result), tool_call_id=tc["id"])
            )

    return response.content


# ── Run ──────────────────────────────────────────────────────────────────────


async def main():
    print()
    print("=" * 60)
    print("STOCHASTIC MULTI-AGENT SYSTEM")
    print("The LLM decides which agents to call and in what order.")
    print("Every run may take a different path.")
    print("=" * 60)
    print()

    result = await orchestrator(
        "Research the current state of AI agents in software engineering. "
        "Analyze the growth trends. Write a brief report."
    )

    print()
    print("=" * 60)
    print("FINAL OUTPUT")
    print("=" * 60)
    print(result)
    print("=" * 60)


if __name__ == "__main__":
    asyncio.run(main())
